/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/room-scene.gltf -k 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/room-scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group name="macbook" position={[1.416, 0.119, -0.464]} rotation={[0, -0.368, 0]} scale={0.118}>
        <mesh name="Cube019" geometry={nodes.Cube019.geometry} material={materials.body} />
        <mesh name="Cube019_1" geometry={nodes.Cube019_1.geometry} material={materials.keys} />
        <mesh name="Cube019_2" geometry={nodes.Cube019_2.geometry} material={materials['key material']} />
        <mesh name="Cube019_3" geometry={nodes.Cube019_3.geometry} material={materials['keyboard bg']} />
        <mesh name="Cube019_4" geometry={nodes.Cube019_4.geometry} material={materials['body smooth']} />
        <mesh name="Cube019_5" geometry={nodes.Cube019_5.geometry} material={materials['touch id chrome ring']} />
        <mesh name="Cube019_6" geometry={nodes.Cube019_6.geometry} material={materials['rubber pads']} />
        <mesh name="Cube019_7" geometry={nodes.Cube019_7.geometry} material={materials['usb metal']} />
        <mesh name="Cube019_8" geometry={nodes.Cube019_8.geometry} material={materials['Black plastic']} />
        <mesh name="macbookJoint" geometry={nodes.macbookJoint.geometry} material={materials['black borders']} scale={1.164}>
          <group name="display" scale={7.306}>
            <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.body} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} />
            <mesh name="Plane_1" geometry={nodes.Plane_1.geometry} material={materials['shiny body']} morphTargetDictionary={nodes.Plane_1.morphTargetDictionary} morphTargetInfluences={nodes.Plane_1.morphTargetInfluences} />
            <mesh name="Plane_2" geometry={nodes.Plane_2.geometry} material={materials['display glass']} morphTargetDictionary={nodes.Plane_2.morphTargetDictionary} morphTargetInfluences={nodes.Plane_2.morphTargetInfluences} />
            <mesh name="Plane_3" geometry={nodes.Plane_3.geometry} material={materials['screen BLUE']} morphTargetDictionary={nodes.Plane_3.morphTargetDictionary} morphTargetInfluences={nodes.Plane_3.morphTargetInfluences} />
            <mesh name="Plane_4" geometry={nodes.Plane_4.geometry} material={materials['camera glass']} morphTargetDictionary={nodes.Plane_4.morphTargetDictionary} morphTargetInfluences={nodes.Plane_4.morphTargetInfluences} />
            <mesh name="Plane_5" geometry={nodes.Plane_5.geometry} material={materials['black borders']} morphTargetDictionary={nodes.Plane_5.morphTargetDictionary} morphTargetInfluences={nodes.Plane_5.morphTargetInfluences} />
            <mesh name="Plane_6" geometry={nodes.Plane_6.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.Plane_6.morphTargetDictionary} morphTargetInfluences={nodes.Plane_6.morphTargetInfluences} />
            <mesh name="Plane_7" geometry={nodes.Plane_7.geometry} material={materials['body smooth']} morphTargetDictionary={nodes.Plane_7.morphTargetDictionary} morphTargetInfluences={nodes.Plane_7.morphTargetInfluences} />
          </group>
        </mesh>
      </group>
      <mesh name="PurpleLEDL" geometry={nodes.PurpleLEDL.geometry} material={materials.PurpleLED} position={[0.132, 0.114, -5.135]} rotation={[0, 0, Math.PI / 2]} />
      <mesh name="PurpleLEDR" geometry={nodes.PurpleLEDR.geometry} material={materials.PurpleLED} position={[8.448, 0.114, 7.11]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh name="Name" geometry={nodes.Name.geometry} material={materials['Material.006']} position={[-0.097, 0.931, -4.983]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="TableLeg" geometry={nodes.TableLeg.geometry} material={materials.TableLeg} position={[8.278, -4.088, -4.969]} />
      <mesh name="LampLeg" geometry={nodes.LampLeg.geometry} material={materials.LampLeg} position={[4.411, 1.104, 3.983]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="LampHead" geometry={nodes.LampHead.geometry} material={materials.LampHead} position={[4.413, 1.933, 3.984]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh name="Ball" geometry={nodes.Ball.geometry} material={materials.Ball} position={[3.374, -4.41, 2.687]} rotation={[1.974, 0.167, 0.561]} />
      <mesh name="BlueLEDL" geometry={nodes.BlueLEDL.geometry} material={materials.BlueLED} position={[0.132, -0.668, -5.277]} rotation={[0, 0, Math.PI / 2]} />
      <mesh name="BlueLEDR" geometry={nodes.BlueLEDR.geometry} material={materials.BlueLED} position={[8.539, -0.668, 7.11]} rotation={[Math.PI / 2, Math.PI / 2, 0]} />
      <mesh name="Table" geometry={nodes.Table.geometry} material={materials.Table} position={[-2.553, -0.108, -2.095]} />
      <group name="SpeakerL1" position={[-2.417, 0.964, -0.534]} rotation={[Math.PI, -1.486, Math.PI / 2]}>
        <mesh name="Circle008" geometry={nodes.Circle008.geometry} material={materials.Speaker1} />
        <mesh name="Circle008_1" geometry={nodes.Circle008_1.geometry} material={materials['Material.017']} />
      </group>
      <mesh name="SpeakerL2" geometry={nodes.SpeakerL2.geometry} material={materials.Speaker2} position={[-2.346, 1.138, -1.375]} rotation={[Math.PI, -1.486, Math.PI]} />
      <group name="SpeakerL3" position={[-2.418, 1.903, -0.527]} rotation={[Math.PI, -1.486, Math.PI / 2]}>
        <mesh name="Circle009" geometry={nodes.Circle009.geometry} material={materials.Speaker1} />
        <mesh name="Circle009_1" geometry={nodes.Circle009_1.geometry} material={materials['Material.017']} />
      </group>
      <group name="SpeakerR1" position={[4.31, 0.99, 1.989]} rotation={[Math.PI, -0.321, Math.PI / 2]}>
        <mesh name="Circle006" geometry={nodes.Circle006.geometry} material={materials.Speaker1} />
        <mesh name="Circle006_1" geometry={nodes.Circle006_1.geometry} material={materials['Material.017']} />
      </group>
      <mesh name="SpeakerR2" geometry={nodes.SpeakerR2.geometry} material={materials.Speaker2} position={[5.111, 1.163, 1.723]} rotation={[Math.PI, -0.321, Math.PI]} />
      <group name="SpeakerR3" position={[4.303, 1.928, 1.992]} rotation={[Math.PI, -0.321, Math.PI / 2]}>
        <mesh name="Circle007" geometry={nodes.Circle007.geometry} material={materials.Speaker1} />
        <mesh name="Circle007_1" geometry={nodes.Circle007_1.geometry} material={materials['Material.017']} />
      </group>
      <mesh name="Room" geometry={nodes.Room.geometry} material={materials.Room} position={[9.464, 1.464, 9.217]} />
    </group>
  )
}

useGLTF.preload('/room-scene.gltf')
